# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
    push:
    pull_request:
        branches: [main]
jobs:
    basic-checks:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version:
                    - 6
                    - 8
                    - 10
                    - 11
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'npm'
            - name: install clean
              if: ${{ matrix.node_version > 6 }}
              run: npm ci
            - name: install dirty
              if: ${{ matrix.node_version == 6 }}
              run: npm install
            - run: node ./test/test.js
    coverage--node:
        name: Node Coverage
        runs-on: ubuntu-latest
        outputs:
            coverage: ${{ steps.coverage--node.outputs.artifact-id }}
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 10
              uses: actions/setup-node@v6
              with:
                  node-version: 10
                  cache: 'npm'
            - run: npm ci
            - run: npm install -g c8@7
            - run: c8 -c ./.c8rc.node.json node ./test/test.js
            - uses: actions/upload-artifact@v4
              id: coverage--node
              with:
                name: coverage--node
                path: ./coverage/node/tmp/*.json
    coverage--playwright:
        name: Browser Coverage
        runs-on: ubuntu-latest
        outputs:
            coverage: ${{ steps.coverage--playwright.outputs.artifact-id }}
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 24
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: 'npm'
            - uses: hoverkraft-tech/compose-action@05da55b2bb8a5a759d1c4732095044bd9018c050
              with:
                services: tests
                cwd: ./.devcontainer/
                compose-file: ./docker-compose.yml
            - name: http check
              id: http-check
              uses: fjogeleit/http-request-action@v1
              with:
                url: "http://localhost:8003"
                method: GET
            - run: echo ${{ steps.http-check.outputs.status }}
            - run: npm ci
            - run: npm install -g playwright@1.57
            - run: playwright install --with-deps --only-shell chromium
            - run: NODE_PATH=$(npm root -g) node ./playwright.js http://localhost:8003
            - uses: actions/upload-artifact@v4
              id: coverage--playwright
              with:
                name: coverage--playwright
                path: ./coverage/playwright/tmp/*.json
    coverage--upload:
        name: Upload Coverage
        runs-on: ubuntu-latest
        needs:
            - coverage--node
            - coverage--playwright
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 10
              uses: actions/setup-node@v6
              with:
                  node-version: 10
                  cache: 'npm'
            - run: npm install -g c8@7
            - name: Download Coverage
              uses: actions/download-artifact@v5
              with:
                  path: ./coverage/tmp/
                  pattern: coverage-*
                  merge-multiple: true
            - run: ls -R ./coverage/tmp/
            - name: Merge Coverage
              run: c8 -c ./.c8rc.coveralls.json report
            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2.2.3
              with:
                  file: './coverage/lcov.info'
